#!/usr/bin/python
import commands

action_to_cmd = {
    'modified' : 'git add ',
    'deleted' : 'git rm --cached '
}

def action_from_output(line):
    args = line.split(':')
    action = args[0].strip()
    f = args[1].strip()
    cmd = action_to_cmd[action]
    cmd = cmd + f
    print cmd
    commands.getstatusoutput(cmd)

status, output = commands.getstatusoutput('git status')
for line in output.split('\n'):
    line = line.strip()
    for key in action_to_cmd.keys():
        if line.startswith(key+":"):
            action_from_output(line)



